"""Initial migration

Revision ID: afb946e2ad2e
Revises: 
Create Date: 2025-05-02 06:02:13.368800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afb946e2ad2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhooks', sa.Column('status', sa.String(), nullable=False, server_default='polling'))
    op.add_column('webhooks', sa.Column('limit_price', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('webhooks', sa.Column('order_id', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('webhooks', 'status', server_default=None)
    op.alter_column('webhooks', 'limit_price', server_default=None)
    op.alter_column('webhooks', 'order_id', server_default=None)
    # ### end Alembic commands ###
